#!/bin/bash
# Quickly shares a list of screens individually.
#
# Eg
# $0 list
# $0 eDP-1
# $0 eDP-1 DP-2

passwdFile=~/.vnc/passwd

function list
{
    xrandr | grep ' connected'
}

function getDevice
{
    cut -d\  -f1
}

function getClip
{
    cut -d'(' -f1 | sed 's/ $//g; s/^.* //g'
}


function start
{
    usepw='-usepw'
    if [ ! -e $passwdFile ]; then
        usepw=''
        echo "$passwdFile doesn't appear to exist, so no password will be required to connect. This isn't safe. I recommend running \`x11vnc -usepw\` to set it."
        for i in {10..1}; do
            echo "Waiting for you to see this message. $i... "
            sleep 1
        done
    fi
    
    x11vnc -loop $usepw -clip "$2" 2>&1 | while read in; do echo "$1: $in"; done
}

function startWrapper
{
    if list | grep -q "$1"; then
        clip=$(list | grep "$1" | getClip)
        start "$1" "$clip" &
    else
        echo "Could not find \"$2\"."
        exit 1
    fi
}

case $1 in
    "list")
        list
    ;;
    *)
        for device in "$@"; do
            startWrapper "$device"
        done
        wait
    ;;
esac
